# docker-compose.yml
version: "3"
services:
#  front:
#    build: ./auth-front/
#    ports:
#      - "42001:3000"
#    command: npm start

  app:
    build: ./
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres:/
      
      NODE_ENV: development
      PORT: 3000
    ports:
      - "42002:3000"
    command: npm run dev
    volumes:
      - .:/app/
      - /app/node_modules

  postgres:
    image: postgres:14.5-bullseye
    ports:
      - "35432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: estacionamento
    volumes: 
      - ./estacionamento.sql:/docker-entrypoint-initdb.d/estacionamento.sql
