# docker-compose.yml
version: "3"
services:
#  front:
#    build: ./auth-front/
#    ports:
#      - "42001:3000"
#    command: npm start

  app:
    build: ./
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://montduser:montd42@postgres:5432/omni_users
      NODE_ENV: development
      PORT: 3000
    ports:
      - "42002:3000"
    command: npm run dev
    volumes:
      - .:/app/
      - /app/node_modules

  postgres:
    image: postgres:14.5-bullseye
    ports:
      - "35432:5432"
    environment:
      POSTGRES_USER: montduser
      POSTGRES_PASSWORD: montd42
      POSTGRES_DB: omni_users
    volumes: 
      - ./omni_users.sql:/docker-entrypoint-initdb.d/omni_users.sql
